---
include:
  - project: 'klausklausen/templates'
    ref: main
    file: 'test.yml'
  - project: 'klausklausen/templates'
    ref: main
    file: 'deploy.yml'
  - project: 'klausklausen/templates'
    ref: main
    file: 'build.yml'
  - project: 'klausklausen/templates'
    ref: main
    file: 'package.yml'
  - project: 'klausklausen/templates'
    ref: main
    file: 'deploy.yml'
  - project: 'klausklausen/templates'
    ref: main
    file: 'lint.yml'
  - project: 'klausklausen/templates'
    ref: main
    file: 'security.yml'

variables:
  TAG: $CI_COMMIT_BRANCH
  GO_IMAGE: golang:1.23

stages:
  - tmp
  - security
  - lint
  - test
  - build
  - package
  - deploy
  - publish

tmp:
  stage: tmp
  image: alpine:latest
  script:
    - echo "This is a temporary job to create the tmp stage"
    - nslookup gitlab.kk.int 10.10.100.220
    - nslookup repo.kk.int 10.10.100.220
    - nslookup gitlab.kk.int
    - nslookup repo.kk.int
    - cat /etc/resolv.conf
  tags:
    - arm64

# lint
markdown lint:
  extends: .markdown_lint
yaml lint:
  extends: .yaml_lint
prettier lint:
  extends: .prettier
helm lint:
  extends: .helm_lint
  variables:
    HELM_CHART_DIR: ./database-backup

# test
render helm chart:
  extends: .render_helm_chart
  variables:
    HELM_CHART_DIR: ./database-backup
  allow_failure: true

# security
package scan:
  extends: .package_scan
secret scan:
  extends: .secret_scan

# package
package helm:
  extends: .package_helm_chart
  variables:
    HELM_CHART_DIR: .
    PACKAGE_NAME: ${CI_PROJECT_NAME}

# deploy
deploy helm:
  extends: .deploy_helm_chart
  variables:
    HELM_CHART_DIR: .
    PACKAGE_NAME: ${CI_PROJECT_NAME}
