{{- $root := . -}}
{{- range $key, $value := .Values.retention }}
  {{- if $value.enabled | default false }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $root.Values.nameOverride }}
  namespace: {{ $root.Values.namespace }}
  labels:
    {{- include "postgres-backup.labels" $ | nindent 4 }}
spec:
  schedule: "@{{ $key }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "postgres-backup.selectorLabels" $ | nindent 12 }}
          annotations:
            {{- toYaml $root.Values.podAnnotations | nindent 12 }}
          labels:
            {{- include "postgres-backup.selectorLabels" $ | nindent 12 }}
        spec:
          imagePullSecrets:
            {{- toYaml $root.Values.imagePullSecrets | nindent 12 }}
          serviceAccountName: {{ include "postgres-backup.serviceAccountName" $ }}
          securityContext:
            {{- toYaml $root.Values.podSecurityContext | nindent 12 }}
          containers:
            - name: "{{ $key }}-create-directory"
              image: "{{ $root.Values.alpineImage.repository }}:{{ $root.Values.alpineImage.tag }}"
              imagePullPolicy: {{ $root.Values.image.pullPolicy }}
              resources:
                {{- toYaml $root.Values.resources | nindent 16 }}
              volumeMounts:
                - name: backupVolume
                  mountPath: /backup
              command:
                - /bin/sh
                - -c
                - mkdir -p /backup/{{ $root.Values.namespace }}/{{ $root.Values.db.database }}/{{ $key }}
            - name: "{{ $key }}-backup"
              image: "{{ $root.Values.image.repository }}:{{ $root.Values.image.tag }}"
              imagePullPolicy: {{ $root.Values.image.pullPolicy }}
              resources:
                {{- toYaml $root.Values.resources | nindent 16 }}
              env:
                - name: POSTGRES_HOST
                  value: {{ $root.Values.db.host }}
                - name: POSTGRES_PORT
                  value: {{ $root.Values.db.port }}
                - name: POSTGRES_USER
                  from:
                    secretKeyRef:
                      name: {{ $root.Values.db.userSecret.name }}
                      key: {{ $root.Values.db.userSecret.key }}
                - name: POSTGRES_PASSWORD
                  from:
                    secretKeyRef:
                      name: {{ $root.Values.db.passwordSecret.name }}
                      key: {{ $root.Values.db.passwordSecret.key }}
                - name: POSTGRES_DB
                  value: {{ $root.Values.db.database }}
              command:
                - /bin/sh
                - -c
                - >-
                  pg_dump 
                    -h $POSTGRES_HOST
                    -p $POSTGRES_PORT
                    -U $POSTGRES_USER $POSTGRES_DB >
                    /backup/{{ $root.Values.namespace }}/{{ $root.Values.db.database }}/{{ $key }}/{{ $root.Values.db.database }}-$(date +%Y%m%d%H%M%S).sql
              volumeMounts:
                - name: backupVolume
                  mountPath: {{ $root.Values.mountPath }}
            - name: "{{ $key }}-delete-old-backups"
              image: "{{ $root.Values.alpineImage.repository }}:{{ $root.Values.alpineImage.tag }}"
              imagePullPolicy: {{ $root.Values.alpineImage.pullPolicy }}
              resources:
                {{- toYaml $root.Values.resources | nindent 16 }}
              env:
                - name: BACKUP_DIR
                  value: /backup/{{ $root.Values.namespace }}/{{ $root.Values.db.database }}/{{ $key }}
                - name: RETENTION
                  value: {{ $key }}
                - name: KEEP
                  value: {{ $value.keep }}
                - name: TZ
                  value: {{ $root.Values.timezone | default "Europe/Berlin" }}
              command:
                - /bin/sh
                - -c
                - >-
                  if [ "$RETENTION" == "yearly" ]; then
                    KEEP=$(($KEEP * 365))
                  elif [ "$RETENTION" == "monthly" ]; then
                    KEEP=$(($KEEP * 30))
                  elif [ "$RETENTION" == "weekly" ]; then
                    KEEP=$(($KEEP * 7 * 24))
                  elif [ "$RETENTION" == "daily" ]; then
                    KEEP=$(($KEEP))
                  elif [ "$RETENTION" == "hourly" ]; then
                    KEEP=$(($KEEP))
                  else
                    echo "No valid retention period given"
                    exit 1
                  fi
                  KEEP=$($KEEP *24 * 60)
                  find $BACKUP_DIR -type f -cmin +$KEEP -exec rm -f {} \;
              volumeMounts:
                - name: backupVolume
                  mountPath: /backup
          volumes:
            - name: backupVolume
              {{- toYaml $root.Values.backupVolume | nindent 14 }}
          restartPolicy: OnFailure
          {{- with $root.Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $root.Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $root.Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
  {{- end }}
{{- end }}